# Generated by Django 5.0 on 2023-12-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=2000)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
