# Generated by Django 5.0 on 2023-12-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='tittle',
            new_name='title',
        ),
    ]
